### ISSUE TITLE
Privs being revoked as of recent update.

### ISSUE THREAD

**Issue by DI3HARD139** [everamzah/dcb#2]
I'm getting reports that players are having certain privs removed when they rejoin. CroGamesVP lost fly and kidmondo lost pretty much all of his/her privs. Was there a recent update to the mod that allows the purchase of privs?

**Comment by everamzah** [comment]
I don't know about the missing privs.  I also don't know whether the /revoke command logs to debug.txt.

However, the playereffects mod has had this problem for me in the past.  A player with applied effects (in this case fast and/or fly) won't be saved if the server shuts down abruptly.  The author noted they weren't particularly interested in further developing the mod, but I may inquire.

As for this case, I was thinking of ways to address this.  The server, at load-time, could check whether a player had applied effects and cancel them.  This would have the undesirable side effect of canceling player's purchased privs during a scheduled shutdown.

I'm not really sure how to go about this particular challenge.

**Comment by DI3HARD139** [comment]
Another method could be to use a save file that the server could log the remaining time to occasionally. as well as what priv said player had active at the time.

**Comment by everamzah** [comment]
Okay, I turned the setting to save player effects on.  1e7a82d0a979691b4c3e83b2036f26a7bf264c9c

**Comment by everamzah** [comment]
@DI3HARD139 https://github.com/everamzah/dcb/blob/176658ce0e8a214369bfed7042197a288e695f45/minetest.conf.example#L65

If you set `playereffects_autosave = 20` it will save every 20 seconds.  I think this is a big disk write, though.

**Comment by Dragonop** [comment]
Offtopic, but as you mentioned players, I should point out that CroGamesVP doesn't deserves that priv, and was already banned by me once.

**Comment by DI3HARD139** [comment]
Ok. I was not aware of that. Privs are auto saving ever 60 secs.
